name: Install Node and package dependencies
description: 'Install Node dependencies with pnpm'

runs:
  using: 'composite'
  steps:
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install packages
      run: npm ci
